version: "3.3"

services:
  app:
    image: weblate/weblate
    volumes:
      - weblate-data:/app/data
    depends_on:
      - database
      - cache
    ports:
      - 80:8080 # TODO remove
    environment:
      WEBLATE_EMAIL_HOST: smtp.mailtrap.io
      WEBLATE_EMAIL_HOST_USER: 8db1d71495d97f
      WEBLATE_EMAIL_HOST_PASSWORD: 31edc97e0e39a0
      WEBLATE_SERVER_EMAIL: localization@tude.club
      WEBLATE_DEFAULT_FROM_EMAIL: localization@tude.club
      WEBLATE_SITE_DOMAIN: localhost
      WEBLATE_ADMIN_PASSWORD: gaming123
      WEBLATE_ADMIN_EMAIL: weblateadmin@tude.club
      REDIS_HOST: cache
      REDIS_PORT: 6379
      POSTGRES_PASSWORD: weblate
      POSTGRES_USER: weblate
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432

  database:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: weblate
      POSTGRES_USER: weblate
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432

  cache:
    image: redis:6-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
      - redis-data:/data

volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
