version: "3.3"

services:
  app:
    image: weblate/weblate
    environment:
      WEBLATE_EMAIL_HOST: smtp.mailtrap.io
      WEBLATE_EMAIL_HOST_USER: 8db1d71495d97f
      WEBLATE_EMAIL_HOST_PASSWORD: 31edc97e0e39a0
      WEBLATE_SERVER_EMAIL: localization@tude.club
      WEBLATE_DEFAULT_FROM_EMAIL: localization@tude.club
      WEBLATE_SITE_DOMAIN: localhost
      WEBLATE_ADMIN_PASSWORD: gaming123
      WEBLATE_ADMIN_EMAIL: weblateadmin@tude.club
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != coyote
          - node.hostname != mc
      update_config:
        parallelism: 1
        delay: 10s

networks:
  proxy:
    external: true
