version: "3.3"

services:
  gaexporter:
    image: ghcr.io/maanex/googleanalytics_exporter:master
    environment:
      GA_VIEWID: "ga:215657062" # google analytics view id
      GA_INTERVAL: 60
      GA_PORT: 80
      GA_METRICS: "rt:pageviews rt:activeUsers"
    ports:
      - 1234:80
    secrets:
      - GA_CREDS

secrets:
  GA_CREDS:
    external: true
