version: "3.3"

services:
  lumberer:
    image: maanex/lumberer:latest
    volumes:
      - logfiles:/storage
    environment:
      STORAGE_PATH: "/storage"
    networks:
      - logging
    deploy:
      labels:

  thumbnailer:
    image: maanex/thumbnailer:latest
    environment:
      FREESTUFF_KEY: "verysecret"
      METRICS_AUTH: "yikes"
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.https.routers.thumbnailer.entrypoints=https
        - traefik.https.routers.thumbnailer.rule=Host(`thumbnails.freestuffbot.xyz`)
        # - traefik.https.routers.thumbnailer.rule=Host(`green.localhost`)
        - traefik.https.services.thumbnailer.loadbalancer.server.port=9915

networks:
  traefik-public:
    external: true
  logging:
    external: true

volumes:
  logfiles: {}
