version: "3.3"

services:
  traefik:
    image: traefik:2.2
    command:
      # - --api.insecure
      - --api.dashboard
      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.metrics.address=:8082
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --metrics.prometheus
      - --metrics.prometheus.entryPoint=metrics
    networks:
      - traefik-public
    ports:
      - 80:80     # web main
      - 443:443     # https
      - 8082:8082 # traefik metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.labels.traefik-public.traefik-public-certificates == true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik-public.traefik-public-certificates=true
        - traefik.enable
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`traefik.infra.maanex.me`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`traefik.infra.maanex.me`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.https.services.traefik-public-https.loadbalancer.server.port=8080
        
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      # - prometheus-data:/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
      # labels:
        # - traefik.enable=true
        # - traefik.docker.network=traefik-public
        # - traefik.http.routers.prometheus.entrypoints=http
        # - traefik.http.routers.prometheus.rule=Host(`red.localhost`)
        # - traefik.http.services.prometheus.loadbalancer.server.port=9090

  grafana:
    image: grafana/grafana
    # depends_on:
    #   - prometheus
    volumes:
      # - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.https.routers.grafana.entrypoints=https
        - traefik.https.routers.grafana.rule=Host(`monitoring.infra.maanex.me`)
        - traefik.https.services.grafana.loadbalancer.server.port=3000


networks:
  traefik-public:
    external: true

volumes:
  prometheus-data: {}
  grafana-data: {}
