file_version = 1
name = "FreeStuff API"

[service]
image = "ghcr.io/freestuffbot/fsb-api:main"

[environment]
NODE_ENV = "production"
FSB_API_PORT = "80"
FSB_API_REDIS_URL = ""
FSB_API_RABBIT_URL = "amqp://rabbitmq"
FSB_API_DASH_CORS_ORIGIN = "https://dashboard.freestuffbot.xyz"
FSB_API_DASH_OAUTH_CALLBACK_URL = "https://dashboard.freestuffbot.xyz/oauth/callback"
FSB_NETWORK_GIBU_GQL_ENDPOINT = "http://gibu_api_games/graphql"
FSB_NETWORK_THUMBNAILER = "http://thumbnailer"
FSB_NETWORK_MANAGER = "http://manager"
FSB_NETWORK_LINK_PROXY = "http://link_proxy"
FSB_NETWORK_SCRAPER = "http://scraper"
FSB_NETWORK_UMI_ALLOWED_IP_RANGE = "10.0.0.0/16"
FSB_API_PRIVATE_KEY_URI = "/run/secrets/FSB_API_PRIVATE_KEY"

[secrets]
FSB_API_MONGO_URL = true
FSB_API_OAUTH_DISCORD_APPID = true
FSB_API_OAUTH_DISCORD_APPSECRET = true
FSB_API_PRIVATE_KEY = true
FSB_API_AUDITLOG_DEST_DISCORD = true
FSB_API_NOTIFICATIONS_DEST_DISCORD = true
FSB_API_HELPER_BOT_TOKEN = true

[networks]
metrics = true
proxy = true
gibu = true
fsn_core = true
fsn_discord = true
fsn_publisher = true

[deploy]
mode = "replicated"
replicas = 1

[deploy.placement]
constraints = [
  "node.labels.autoscale==true"
]

[deploy.updates]
parallelism = 1
delay = "30s"

[deploy.labels]
"xyz.freestuffbot.service.role" = "api"
"prometheus-job" = "fsb"
"traefik.enable" = true
"traefik.docker.network" = "proxy"
"traefik.http.services.fsb-api.loadbalancer.server.port" = 80
"traefik.http.routers.fsb-api.entrypoints" = "https"
"traefik.http.routers.fsb-api.rule" = "Host(`api.freestuffbot.xyz`)"
"traefik.http.routers.fsb-api.tls.certresolver" = "cloudflare"
"traefik.http.routers.fsb-api.tls.domains[0].main" = "api.freestuffbot.xyz"
