version: "3.3"

services:
  db:
    image: postgres
    networks:
      - net
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    deploy:
      mode: replicated
      replicas: 1
      restart: always

  app:
    image: nextcloud
    networks:
      - net
      - proxy
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      restart: always
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.cloud.loadbalancer.server.port=80
        - traefik.http.routers.cloud.entrypoints=https
        - traefik.http.routers.cloud.rule=Host(`cloud.maanex.me`)
        - traefik.http.routers.cloud.tls.certresolver=cloudflare
        - traefik.http.routers.cloud.tls.domains[0].main=cloud.maanex.me

  cron:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      restart: always


networks:
  net:
    driver: overlay
    attachable: true
  proxy:
    external: true

volumes:
  nextcloud: {}
  db: {}
