version: "3.9"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    networks:
      - db
      - proxy
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://coder:${CODER_POSTGRES_PASSWORD}@database/coder?sslmode=disable"
      CODER_ADDRESS: "0.0.0.0:3000"
      CODER_ACCESS_URL: "https://tudedev.xyz"
      CODER_WILDCARD_ACCESS_URL: "*.tudedev.xyz"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/services/deployment/production/coder/:/home/coder/
    depends_on:
      - database

    deploy:
      placement:
        constraints:
          - node.hostname == co2
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.tudedev.loadbalancer.server.port=3000
        - traefik.http.routers.tudedev.entrypoints=https
        - traefik.http.routers.tudedev.rule=Host(`tudedev.xyz`)
        - traefik.http.routers.tudedev.rule=HostRegexp(`^.+\.tudedev\.xyz$$`)
        - traefik.http.routers.tudedev.tls.certresolver=cloudflare
        - traefik.http.routers.tudedev.tls.domains[0].main=tudedev.xyz

  database:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: ${CODER_POSTGRES_PASSWORD}
      POSTGRES_DB: coder
    volumes:
      - coder_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U coder -d coder" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  coder_data:

networks:
  proxy:
    external: true
  db:
    driver: overlay
