version: "3.9"

volumes:
  coder_data:

networks:
  proxy:
    external: true
  db:
    driver: overlay

services:
  coder:
    image: ghcr.io/coder/coder:latest
    networks:
      - db
      - proxy
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://coder:${CODER_POSTGRES_PASSWORD}@database/coder?sslmode=disable"
      CODER_ADDRESS: "0.0.0.0:3000"
      CODER_ACCESS_URL: "https://dev.tude.club"
      CODER_WILDCARD_ACCESS_URL: "*.dev.tude.club"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database

    deploy:
      placement:
        constraints:
          - node.role==manager
          - node.labels.autoscale==true
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.tudedev.loadbalancer.server.port=3000
        - traefik.http.routers.tudedev.entrypoints=https
        # - traefik.http.routers.tudedev.rule=Host(`dev.tude.club`)
        - traefik.http.routers.tudedev.rule=HostRegexp(`{host:^(.+\.)?dev\.tude\.club$$}`)
        - traefik.http.routers.tudedev.tls.certresolver=cloudflare
        - traefik.http.routers.tudedev.tls.domains[0].main=dev.tude.club

  database:
    image: "postgres:14.2"
    networks:
      - db
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: ${CODER_POSTGRES_PASSWORD}
      POSTGRES_DB: coder
    volumes:
      - coder_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U coder -d coder" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.autoscale==true
          - node.labels.persistent==true
