version: "3.3"

services:
  fsdiscord:
    image: ghcr.io/freestuffbot/legacy:master
    environment:
      NODE_ENV: "production"
      NODE_ID: "co1"
      FSB_REDIS_HOST: "redis"
      FSB_WORKER_HOST: "ws://manager:9002"
      FSB_SERVER_ENABLE: "true"
      FSB_SERVER_PORT: "80"
      FSB_METRICS_ENDPOINT: "/metrics"
    networks:
      - redis
      - fsm-sockets
      - metrics
    secrets:
      - FSB_DBOT_TOKEN
      - FSB_DBOT_ID
      - FSB_MONGO_URL
      - FSB_FSAPI_KEY
      - FSB_SENTRY_DSN
    deploy:
      mode: replicated
      replicas: 4
      labels:
        - prometheus-job=fsb
      placement:
        constraints:
          - node.hostname == co1
      update_config:
        parallelism: 1
        delay: 30s

networks:
  redis:
    external: true
  fsm-sockets:
    external: true
  metrics:
    external: true

secrets:
  FSB_DBOT_TOKEN:
    external: true
  FSB_DBOT_ID:
    external: true
  FSB_MONGO_URL:
    external: true
  FSB_FSAPI_KEY:
    external: true
  FSB_SENTRY_DSN:
    external: true
