version: "3.9"

services:
  mongodb:
    image: mongo:latest
    networks:
      - devenv
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    # ports:
    #   - 27017:27017
    volumes:
      - devenv_mongo:/data/db

    # deploy:
    #   placement:
    #     constraints:
    #       - node.hostname == co2

volumes:
  devenv_mongo:

networks:
  devenv:
    external: true
