version: "3.9"

services:
  mongodb:
    image: mongo:latest
    networks:
      - devenv
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - devenv_mongo:/data/db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co2

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - devenv
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co2

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - devenv
    volumes:
      - devenv_postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co2

  # chrome:
  #   image: zenika/alpine-chrome:with-puppeteer
  #   entrypoint: [
  #     "chromium-browser",
  #     "--headless",
  #     "--disable-gpu",
  #     "--disable-software-rasterizer",
  #     "--disable-dev-shm-usage",
  #     "--no-sandbox",
  #     "--remote-debugging-address=0.0.0.0",
  #     "--remote-debugging-port=9222"
  #   ]
  #   networks:
  #     - devenv
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.hostname == co2


volumes:
  devenv_mongo:
  devenv_postgres:

networks:
  devenv:
    external: true
