version: "3.3"

services:
  deployman:
    image: ghcr.io/maanex/deployman:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/services/deployman:/data
    environment:
      - DEPLOYMAN_PORT=80
      - DEPLOYMAN_DISCORD_CLIENT_ID=961357255817707540
      - DEPLOYMAN_DISCORD_PUBIC_KEY=d0a4ab69ac4248100d932139d984e68e6cacb694a5c57b83a4835ee71691176c
      - DEPLOYMAN_PRODUCT_CONFIG_PATH=/data/productconfig.yaml
    networks:
      - proxy
    secrets:
      - DEPLOYMAN_DISCORD_BOT_TOKEN
      - DEPLOYMAN_REGISTRY_AUTH
      - DEPLOYMAN_GITHUB_WEBHOOK_SECRET
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.deployman.loadbalancer.server.port=80
        - traefik.http.routers.deployman.entrypoints=https
        - traefik.http.routers.deployman.rule=Host(`deployman.tude.network`)
        - traefik.http.routers.deployman.tls.certresolver=cloudflare
        - traefik.http.routers.deployman.tls.domains[0].main=deployman.tude.network

networks:
  proxy:
    external: true

secrets:
  DEPLOYMAN_DISCORD_BOT_TOKEN:
    external: true
  DEPLOYMAN_REGISTRY_AUTH:
    external: true
  DEPLOYMAN_GITHUB_WEBHOOK_SECRET:
    external: true
