version: "3.9"

services:
  mongodb:
    image: mongo:latest
    networks:
      - devenv
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - devenv_mongo:/data/db

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - devenv
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co2


volumes:
  devenv_mongo:

networks:
  devenv:
    external: true
