version: "3.3"

services:
  api:
    image: ghcr.io/freestuffbot/fsb-api:master
    environment:
      NODE_ENV: "production"
      FSB_API_PORT: "80"
      FSB_API_REDIS_URL: "redis://infra_redis"
      FSB_API_RABBIT_URL: "amqp://infra_rabbit"
      FSB_API_DASH_CORS_ORIGIN: "https://dashboard.freestuffbot.xyz"
      FSB_API_DASH_OAUTH_CALLBACK_URL: "https://dashboard.freestuffbot.xyz/oauth/callback"
      FSB_NETWORK_GIBU_GQL_ENDPOINT: "http://gibu_api_games/graphql"
      FSB_NETWORK_THUMBNAILER: "http://thumbnailer"
      FSB_NETWORK_MANAGER: "http://manager"
      FSB_NETWORK_LINK_PROXY: "http://link_proxy"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_API_PRIVATE_KEY_URI: "/run/secrets/FSB_API_PRIVATE_KEY"
    networks:
      - redis
      - rabbits
      - metrics
      - proxy
      - gibu
      - fsn_core
      - fsn_discord
      - fsn_publisher
    secrets:
      - FSB_API_MONGO_URL
      - FSB_API_OAUTH_DISCORD_APPID
      - FSB_API_OAUTH_DISCORD_APPSECRET
      - FSB_API_PRIVATE_KEY
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=api
        - prometheus-job=fsb
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.fsb-api.loadbalancer.server.port=80
        - traefik.http.routers.fsb-api.entrypoints=https
        - traefik.http.routers.fsb-api.rule=Host(`api.freestuffbot.xyz`)
        - traefik.http.routers.fsb-api.tls.certresolver=cloudflare
        - traefik.http.routers.fsb-api.tls.domains[0].main=api.freestuffbot.xyz

  manager:
    image: ghcr.io/freestuffbot/fsb-manager:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NODE_ENV: "production"
      FSB_MANAGER_PORT: "80"
    networks:
      - fsn_core
      - fsn_discord
    secrets:
      - FSB_MANAGER_MONGO_URL
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname == coyote
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=manager
        - prometheus-job=fsb

  discord_interactions:
    image: ghcr.io/freestuffbot/fsb-discord-interactions:master
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_INTERACTIONS_PORT: "80"
      FSB_DISCORD_INTERACTIONS_RABBIT_URL: "amqp://infra_rabbit"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_NETWORK_DISCORD_GATEWAY: "http://discord_gateway"
      FSB_DISCORD_INTERACTIONS_FREESTUFF_API_URL: "http://api"
      FSB_DISCORD_INTERACTIONS_CLIENTID: "672822334641537041"
      FSB_DISCORD_INTERACTIONS_PUBKEY: "12b1f94e6026ec780e65f0fa676b966ad00e3803e5e42a80745216eaa45db595"
    networks:
      - rabbits
      - metrics
      - proxy
      - fsn_discord
    secrets:
      - FSB_DISCORD_INTERACTIONS_MONGO_URL
      - FSB_DISCORD_INTERACTIONS_FREESTUFF_API_KEY
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-interactions
        - prometheus-job=fsb
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.fsb-discord-interactions.loadbalancer.server.port=80
        - traefik.http.routers.fsb-discord-interactions.entrypoints=https
        - traefik.http.routers.fsb-discord-interactions.rule=Host(`inbound-discord--net.freestuffbot.xyz`)
        - traefik.http.routers.fsb-discord-interactions.tls.certresolver=cloudflare
        - traefik.http.routers.fsb-discord-interactions.tls.domains[0].main=inbound-discord--net.freestuffbot.xyz

  discord_gateway:
    image: ghcr.io/freestuffbot/fsb-discord-gateway:master
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_GATEWAY_PORT: "80"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_discord
    secrets:
      - FSB_DISCORD_GATEWAY_API_TOKEN
      - FSB_DISCORD_GATEWAY_API_USER
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-gateway
        - prometheus-job=fsb

  discord_publisher:
    image: ghcr.io/freestuffbot/fsb-discord-publisher:master
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_PUBLISHER_RABBIT_URL: "amqp://infra_rabbit"
      FSB_DISCORD_PUBLISHER_FREESTUFF_API_URL: "http://api"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - rabbits
      - fsn_publisher
    secrets:
      - FSB_DISCORD_PUBLISHER_MONGO_URL
      - FSB_DISCORD_PUBLISHER_FREESTUFF_API_KEY
    depends_on:
      - api
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != coyote
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-publisher
        - prometheus-job=fsb

  app_publisher:
    image: ghcr.io/freestuffbot/fsb-app-publisher:master
    environment:
      NODE_ENV: "production"
      FSB_APP_PUBLISHER_RABBIT_URL: "amqp://infra_rabbit"
      FSB_APP_PUBLISHER_FREESTUFF_API_URL: "http://api"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    depends_on:
      - api
    networks:
      - metrics
      - rabbits
      - fsn_publisher
    secrets:
      - FSB_APP_PUBLISHER_MONGO_URL
      - FSB_APP_PUBLISHER_FREESTUFF_API_KEY
      - FSB_APP_PUBLISHER_UPSTREAM_URL
      - FSB_APP_PUBLISHER_UPSTREAM_AUTH
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=app-publisher
        - prometheus-job=fsb

  thumbnailer:
    image: ghcr.io/freestuffbot/fsb-thumbnailer:master
    environment:
      NODE_ENV: "production"
      FSB_THUMBNAILER_PORT: "80"
      FSB_THUMBNAILER_DISCORD_CDN_CHANNEL: "885829282952278038"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_THUMBNAILER_DISCORD_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=thumbnailer
        - prometheus-job=fsb

  link_proxy:
    image: ghcr.io/freestuffbot/fsb-link-proxy:master
    environment:
      NODE_ENV: "production"
      FSB_LINK_PROXY_PORT: "80"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_LINK_PROXY_MONGO_URL
      - FSB_LINK_PROXY_FIREBASE_API_KEY
      - FSB_LINK_PROXY_FIREBASE_SERVICE_ACCOUNT_KEY
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=link-proxy
        - prometheus-job=fsb

networks:
  # access to "external" services
  redis:
    external: true
  rabbits:
    external: true
  metrics:
    external: true
  proxy:
    external: true
  gibu:
    external: true
  # freestuff network -> internal communication
  fsn_core:
    driver: overlay
  fsn_tools:
    driver: overlay
  fsn_discord:
    driver: overlay
  fsn_publisher:
    driver: overlay

secrets:
  # API
  FSB_API_MONGO_URL:
    external: true
  FSB_API_OAUTH_DISCORD_APPID:
    external: true
  FSB_API_OAUTH_DISCORD_APPSECRET:
    external: true
  FSB_API_PRIVATE_KEY:
    external: true
  # MANAGER
  FSB_MANAGER_MONGO_URL:
    external: true
  # DISCORD INTERACTIONS
  FSB_DISCORD_INTERACTIONS_MONGO_URL:
    external: true
  FSB_DISCORD_INTERACTIONS_FREESTUFF_API_KEY:
    external: true
  # DISCORD GATEWAY
  FSB_DISCORD_GATEWAY_API_TOKEN:
    external: true
  FSB_DISCORD_GATEWAY_API_USER:
    external: true
  # DISCORD PUBLISHER
  FSB_DISCORD_PUBLISHER_MONGO_URL:
    external: true
  FSB_DISCORD_PUBLISHER_FREESTUFF_API_KEY:
    external: true
  # APP PUBLISHER
  FSB_APP_PUBLISHER_MONGO_URL:
    external: true
  FSB_APP_PUBLISHER_FREESTUFF_API_KEY:
    external: true
  FSB_APP_PUBLISHER_UPSTREAM_URL:
    external: true
  FSB_APP_PUBLISHER_UPSTREAM_AUTH:
    external: true
  # THUMBNAILER
  FSB_THUMBNAILER_DISCORD_TOKEN:
    external: true
  # LINK PROXY
  FSB_LINK_PROXY_MONGO_URL:
    external: true
  FSB_LINK_PROXY_FIREBASE_API_KEY:
    external: true
  FSB_LINK_PROXY_FIREBASE_SERVICE_ACCOUNT_KEY:
    external: true
