version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.8
    hostname: rabbit
    networks:
      - fsn_discord
      - fsn_publisher
      - fsn_tools
    deploy:
      placement:
        constraints:
          - node.role == manager

  api:
    image: ghcr.io/freestuffbot/fsb-api:main
    environment:
      NODE_ENV: "production"
      FSB_API_PORT: "80"
      FSB_API_REDIS_URL: ""
      FSB_API_RABBIT_URL: "amqp://rabbitmq"
      FSB_API_DASH_CORS_ORIGIN: "https://dashboard.freestuffbot.xyz"
      FSB_API_DASH_OAUTH_CALLBACK_URL: "https://dashboard.freestuffbot.xyz/oauth/callback"
      FSB_NETWORK_GIBU_GQL_ENDPOINT: "http://gibu_api_games/graphql"
      FSB_NETWORK_THUMBNAILER: "http://thumbnailer"
      FSB_NETWORK_MANAGER: "http://manager"
      FSB_NETWORK_LINK_PROXY: "http://link_proxy"
      FSB_NETWORK_SCRAPER: "http://scraper"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_API_PRIVATE_KEY_URI: "/run/secrets/FSB_API_PRIVATE_KEY"
    networks:
      - metrics
      - proxy
      - gibu
      - fsn_core
      - fsn_discord
      - fsn_publisher
    secrets:
      - FSB_API_MONGO_URL
      - FSB_API_OAUTH_DISCORD_APPID
      - FSB_API_OAUTH_DISCORD_APPSECRET
      - FSB_API_PRIVATE_KEY
      - FSB_API_AUDITLOG_DEST_DISCORD
      - FSB_API_NOTIFICATIONS_DEST_DISCORD
      - FSB_API_HELPER_BOT_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=api
        - prometheus-job=fsb
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.fsb-api.loadbalancer.server.port=80
        - traefik.http.routers.fsb-api.entrypoints=https
        - traefik.http.routers.fsb-api.rule=Host(`api.freestuffbot.xyz`)
        - traefik.http.routers.fsb-api.tls.certresolver=cloudflare
        - traefik.http.routers.fsb-api.tls.domains[0].main=api.freestuffbot.xyz

  manager:
    image: ghcr.io/freestuffbot/fsb-manager:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NODE_ENV: "production"
      FSB_MANAGER_PORT: "80"
      FSB_MANAGER_RABBIT_URL: "amqp://rabbitmq"
    networks:
      - fsn_core
      - fsn_discord
    secrets:
      - FSB_MANAGER_MONGO_URL
      - FSB_WEBHOOK_SERVICES
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname == coyote
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=manager
        - prometheus-job=fsb

  discord_interactions:
    image: ghcr.io/freestuffbot/fsb-discord-interactions:main
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_INTERACTIONS_PORT: "80"
      FSB_DISCORD_INTERACTIONS_RABBIT_URL: "amqp://rabbitmq"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_NETWORK_DISCORD_GATEWAY: "http://discord_gateway"
      FSB_DISCORD_INTERACTIONS_FREESTUFF_API_URL: "http://api"
      FSB_DISCORD_INTERACTIONS_CLIENTID: "672822334641537041"
      FSB_DISCORD_INTERACTIONS_PUBKEY: "12b1f94e6026ec780e65f0fa676b966ad00e3803e5e42a80745216eaa45db595"
    networks:
      - metrics
      - proxy
      - fsn_discord
    secrets:
      - FSB_WEBHOOK_VOUCHERS
      - FSB_DISCORD_INTERACTIONS_MONGO_URL
      - FSB_DISCORD_INTERACTIONS_FREESTUFF_API_KEY
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-interactions
        - prometheus-job=fsb
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.fsb-discord-interactions.loadbalancer.server.port=80
        - traefik.http.routers.fsb-discord-interactions.entrypoints=https
        - traefik.http.routers.fsb-discord-interactions.rule=Host(`inbound-discord--net.freestuffbot.xyz`)
        - traefik.http.routers.fsb-discord-interactions.tls.certresolver=cloudflare
        - traefik.http.routers.fsb-discord-interactions.tls.domains[0].main=inbound-discord--net.freestuffbot.xyz

  discord_gateway:
    image: ghcr.io/freestuffbot/fsb-discord-gateway:main
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_GATEWAY_PORT: "80"
      FSB_DISCORD_GATEWAY_RABBIT_URL: "amqp://rabbitmq"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_discord
      - fsn_publisher
    secrets:
      - FSB_DISCORD_GATEWAY_API_TOKEN
      - FSB_DISCORD_GATEWAY_API_USER
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-gateway
        - prometheus-job=fsb

  discord_publisher:
    image: ghcr.io/freestuffbot/fsb-discord-publisher:main
    environment:
      NODE_ENV: "production"
      FSB_DISCORD_PUBLISHER_RABBIT_URL: "amqp://rabbitmq"
      FSB_DISCORD_PUBLISHER_FREESTUFF_API_URL: "http://api"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_NETWORK_DISCORD_GATEWAY: "http://discord_gateway"
    networks:
      - metrics
      - fsn_publisher
    secrets:
      - FSB_DISCORD_PUBLISHER_MONGO_URL
      - FSB_DISCORD_PUBLISHER_FREESTUFF_API_KEY
    depends_on:
      - api
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != coyote
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=discord-publisher
        - prometheus-job=fsb

  app_publisher:
    image: ghcr.io/freestuffbot/fsb-app-publisher:main
    environment:
      NODE_ENV: "production"
      FSB_APP_PUBLISHER_RABBIT_URL: "amqp://rabbitmq"
      FSB_APP_PUBLISHER_FREESTUFF_API_URL: "http://api"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    depends_on:
      - api
    networks:
      - metrics
      - fsn_publisher
    secrets:
      - FSB_APP_PUBLISHER_MONGO_URL
      - FSB_APP_PUBLISHER_FREESTUFF_API_KEY
      - FSB_APP_PUBLISHER_UPSTREAM_URL
      - FSB_APP_PUBLISHER_UPSTREAM_AUTH
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=app-publisher
        - prometheus-job=fsb

  # telegram_publisher:
  #   image: ghcr.io/freestuffbot/fsb-telegram-publisher:main
  #   environment:
  #     NODE_ENV: "production"
  #     FSB_NODE_ENV: "production"
  #     FSB_TELEGRAM_PUBLISHER_PORT: "80"
  #     FSB_TELEGRAM_PUBLISHER_RABBIT_URL: "amqp://rabbitmq"
  #     FSB_TELEGRAM_PUBLISHER_FREESTUFF_API_URL: "http://api"
  #     FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
  #   depends_on:
  #     - api
  #   networks:
  #     - metrics
  #     - fsn_publisher
  #   secrets:
  #     - FSB_TELEGRAM_PUBLISHER_FREESTUFF_API_KEY
  #     - FSB_TELEGRAM_PUBLISHER_TELEGRAM_BOT_TOKEN
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 30s
  #     labels:
  #       - xyz.freestuffbot.service.role=telegram-publisher
  #       - prometheus-job=fsb

  thumbnailer:
    image: ghcr.io/freestuffbot/fsb-thumbnailer:main
    environment:
      NODE_ENV: "production"
      FSB_THUMBNAILER_PORT: "80"
      FSB_THUMBNAILER_RABBIT_URL: "amqp://rabbitmq"
      FSB_THUMBNAILER_DISCORD_CDN_CHANNEL: "1066018140129079296"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_THUMBNAILER_DISCORD_TOKEN
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=thumbnailer
        - prometheus-job=fsb

  link_proxy:
    image: ghcr.io/freestuffbot/fsb-link-proxy:main
    environment:
      NODE_ENV: "production"
      FSB_LINK_PROXY_PORT: "80"
      FSB_LINK_PROXY_RABBIT_URL: "amqp://rabbitmq"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_LINK_PROXY_MONGO_URL
      - FSB_LINK_PROXY_FIREBASE_API_KEY
      - FSB_LINK_PROXY_FIREBASE_SERVICE_ACCOUNT_KEY
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=link-proxy
        - prometheus-job=fsb

  scraper:
    image: ghcr.io/freestuffbot/fsb-scraper:main
    environment:
      NODE_ENV: "production"
      FSB_SCRAPER_PORT: "80"
      FSB_SCRAPER_RABBIT_URL: "amqp://rabbitmq"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
      FSB_NETWORK_PUPPETEER: "http://disabled_todo"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_SCRAPER_MONGO_URL
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=scraper
        - prometheus-job=fsb

  butler:
    image: ghcr.io/freestuffbot/fsb-butler:main
    environment:
      NODE_ENV: "production"
      FSB_BUTLER_PORT: "80"
      FSB_BUTLER_RABBIT_URL: "amqp://rabbitmq"
      FSB_BUTLER_CLIENT_ID: "1086629360523554826"
      FSB_BUTLER_FREESTUFF_API_URL: "http://api"
      FSB_NETWORK_UMI_ALLOWED_IP_RANGE: "10.0.0.0/16"
    networks:
      - metrics
      - fsn_tools
    secrets:
      - FSB_BUTLER_MONGO_URL
      - FSB_BUTLER_TOKEN
      - FSB_BUTLER_FREESTUFF_API_KEY
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - xyz.freestuffbot.service.role=butler
        - prometheus-job=fsb

networks:
  # access to "external" services
  metrics:
    external: true
  proxy:
    external: true
  gibu:
    external: true
  # freestuff network -> internal communication
  fsn_core:
    driver: overlay
  fsn_tools:
    driver: overlay
  fsn_discord:
    driver: overlay
  fsn_publisher:
    driver: overlay

secrets:
  # MULTI PURPOSE
  FSB_WEBHOOK_VOUCHERS:
    external: true
  FSB_WEBHOOK_SERVICES:
    external: true

  # API
  FSB_API_MONGO_URL:
    external: true
  FSB_API_OAUTH_DISCORD_APPID:
    external: true
  FSB_API_OAUTH_DISCORD_APPSECRET:
    external: true
  FSB_API_PRIVATE_KEY:
    external: true
  FSB_API_AUDITLOG_DEST_DISCORD:
    external: true
  FSB_API_NOTIFICATIONS_DEST_DISCORD:
    external: true
  FSB_API_HELPER_BOT_TOKEN:
    external: true
  # MANAGER
  FSB_MANAGER_MONGO_URL:
    external: true
  # DISCORD INTERACTIONS
  FSB_DISCORD_INTERACTIONS_MONGO_URL:
    external: true
  FSB_DISCORD_INTERACTIONS_FREESTUFF_API_KEY:
    external: true
  # DISCORD GATEWAY
  FSB_DISCORD_GATEWAY_API_TOKEN:
    external: true
  FSB_DISCORD_GATEWAY_API_USER:
    external: true
  # DISCORD PUBLISHER
  FSB_DISCORD_PUBLISHER_MONGO_URL:
    external: true
  FSB_DISCORD_PUBLISHER_FREESTUFF_API_KEY:
    external: true
  # APP PUBLISHER
  FSB_APP_PUBLISHER_MONGO_URL:
    external: true
  FSB_APP_PUBLISHER_FREESTUFF_API_KEY:
    external: true
  FSB_APP_PUBLISHER_UPSTREAM_URL:
    external: true
  FSB_APP_PUBLISHER_UPSTREAM_AUTH:
    external: true
  # TELEGRAM PUBLISHER
  FSB_TELEGRAM_PUBLISHER_FREESTUFF_API_KEY:
    external: true
  FSB_TELEGRAM_PUBLISHER_TELEGRAM_BOT_TOKEN:
    external: true
  # THUMBNAILER
  FSB_THUMBNAILER_DISCORD_TOKEN:
    external: true
  # LINK PROXY
  FSB_LINK_PROXY_MONGO_URL:
    external: true
  FSB_LINK_PROXY_FIREBASE_API_KEY:
    external: true
  FSB_LINK_PROXY_FIREBASE_SERVICE_ACCOUNT_KEY:
    external: true
  # SCRAPER
  FSB_SCRAPER_MONGO_URL:
    external: true
  # BUTLER
  FSB_BUTLER_MONGO_URL:
    external: true
  FSB_BUTLER_TOKEN:
    external: true
  FSB_BUTLER_FREESTUFF_API_KEY:
    external: true
