version: "3.3"

services:
  api:
    image: ghcr.io/freestuffbot/fsb-api:master
    environment:
      NODE_ENV: "production"
      FSB_API_PORT: "80"
      FSB_API_REDIS_URL: "redis://infra_redis"
      FSB_API_RABBIT_URL: "amqp://infra_rabbit"
      FSB_API_DASH_CORS_ORIGIN: "https://deploy-preview-2--freestuffdash.netlify.app"
      FSB_API_DASH_OAUTH_CALLBACK_URL: "https://deploy-preview-2--freestuffdash.netlify.app/oauth/callback"
      # FSB_API_DASH_CORS_ORIGIN: "https://dashboard.freestuffbot.xyz"
      # FSB_API_DASH_OAUTH_CALLBACK_URL: "https://dashboard.freestuffbot.xyz/oauth/callback"
      FSB_NETWORK_GIBU_GQL_ENDPOINT: "http://gibu_api_games/graphql"
      FSB_NETWORK_THUMBNAILER: "http://thumbnailer"
      FSB_NETWORK_LINK_PROXY: "http://link_proxy"
      FSB_API_PRIVATE_KEY_URI: "/run/secrets/FSB_API_PRIVATE_KEY"
    networks:
      - redis
      - rabbits
      - metrics
      - proxy
      - gibu
    secrets:
      - FSB_API_MONGO_URL
      - FSB_API_OAUTH_DISCORD_APPID
      - FSB_API_OAUTH_DISCORD_APPSECRET
      - FSB_API_PRIVATE_KEY
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - prometheus-job=fsb
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.fsb-api.loadbalancer.server.port=80
        - traefik.http.routers.fsb-api.entrypoints=https
        - traefik.http.routers.fsb-api.rule=Host(`api-v2.freestuffbot.xyz`)
        - traefik.http.routers.fsb-api.tls.certresolver=cloudflare
        - traefik.http.routers.fsb-api.tls.domains[0].main=api-v2.freestuffbot.xyz

networks:
  redis:
    external: true
  rabbits:
    external: true
  metrics:
    external: true
  proxy:
    external: true
  gibu:
    external: true

secrets:
  FSB_API_MONGO_URL:
    external: true
  FSB_API_OAUTH_DISCORD_APPID:
    external: true
  FSB_API_OAUTH_DISCORD_APPSECRET:
    external: true
  FSB_API_PRIVATE_KEY:
    external: true
