version: "3.3"

services:
  runner_chrome:
    image: zenika/alpine-chrome
    entrypoint: [
      "chromium-browser",
      "--headless",
      "--disable-gpu",
      "--disable-software-rasterizer",
      "--disable-dev-shm-usage",
      "--no-sandbox",
      "--remote-debugging-address=0.0.0.0",
      "--remote-debugging-port=9222"
    ]
    networks:
      - gibu

  api_games:
    image: ghcr.io/maanex-gibu/api_games:master
    environment:
      - PORT=80
      - RUNNER_CHROME_ADDR=runner_chrome:9222
    networks:
      - gibu
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 10s

  api_pipeline:
    image: ghcr.io/maanex-gibu/api_pipeline:master
    environment:
      - PORT=80
    networks:
      - gibu
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 10s

networks:
  gibu:
    external: true
