version: "3.3"

services:
  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  rabbit:
    image: rabbitmq:3.8
    hostname: rabbit
    networks:
      rabbits:
        aliases:
          - rabbit
          - infra_rabbit
    deploy:
      placement:
        constraints:
          - node.role == manager


networks:
  redis:
    external: true
  rabbits:
    external: true

volumes:
  redis-data: {}
