version: "3.3"

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    networks:
      - db
    volumes:
      - keycloack_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
      - PROXY_ADRESS_FORWARDING=true
    networks:
      - db
      - proxy
    command: start --proxy edge --hostname-url https://account.tude.club/
    volumes:
      - keycloack_app_data:/opt/jboss/keycloak/standalone/data/
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.entrypoints=https
        - traefik.http.routers.keycloak.rule=Host(`account.tude.club`)
        - traefik.http.routers.keycloak.tls.certresolver=cloudflare
        - traefik.http.routers.keycloak.tls.domains[0].main=account.tude.club

volumes:
  keycloack_postgres_data:
  keycloack_app_data:

networks:
  proxy:
    external: true
  db:
    driver: overlay
