version: "3.3"

services:
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.20.2"
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: udp
        mode: host
      - target: 80
        published: 8083
        mode: host
    volumes:
      - /root/data:/data
    networks:
      - proxy
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '3.5'
          memory: 6G
        reservations:
          cpus: '3'
          memory: 4G
      placement:
        constraints:
          - node.labels.t_mchost==true
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.mcweb.loadbalancer.server.port=80
        - traefik.http.routers.mcweb.entrypoints=https
        - traefik.http.routers.mcweb.rule=Host(`minecraft.tude.club`)
        - traefik.http.routers.mcweb.tls.certresolver=cloudflare
        - traefik.http.routers.mcweb.tls.domains[0].main=minecraft.tude.club


networks:
  proxy:
    external: true
