version: "3.3"

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - /root/services/deployment/production/prometheus/:/etc/prometheus/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - metrics
      - proxy # REMOVE
    deploy:
      placement:
        constraints:
        - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.prom.loadbalancer.server.port=9090
        - traefik.http.routers.prom.entrypoints=https
        - traefik.http.routers.prom.rule=Host(`debug-a1.tude.network`)
        - traefik.http.routers.prom.tls.certresolver=cloudflare
        - traefik.http.routers.prom.tls.domains[0].main=debug-a1.tude.network

  grafana:
    image: grafana/grafana
    # depends_on:
    #   - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - /root/services/deployment/production/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /root/services/deployment/production/grafana/config.monitoring
    networks:
      - proxy
      - metrics
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.routers.grafana.rule=Host(`monitoring.freestuffbot.xyz`)
        - traefik.http.routers.grafana.tls.certresolver=cloudflare
        - traefik.http.routers.grafana.tls.domains[0].main=monitoring.freestuffbot.xyz


networks:
  proxy:
    external: true
  redis:
    external: true
  metrics:
    external: true

volumes:
  prometheus-data: {}
  grafana-data: {}
