version: "3.3"
services:
  plausible_db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    volumes:
      - event-data:/var/lib/clickhouse
      - ./plausible/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./plausible/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    environment:
      BASE_URL: debug-c3.tude.network
      SECRET_KEY_BASE: ${PLAUSIBLE_SECRET}
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.plausible.loadbalancer.server.port=8000
        - traefik.http.routers.plausible.entrypoints=https
        - traefik.http.routers.plausible.rule=Host(`debug-c3.tude.network`)
        - traefik.http.routers.plausible.tls.certresolver=cloudflare
        - traefik.http.routers.plausible.tls.domains[0].main=debug-c3.tude.network

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
