version: "3.3"

services:
  maanexspace:
    image: ghcr.io/maanex/space-backend:master
    environment:
      MNXSPACE_FRONTEND_URL: 'https://space.maanex.me'
      MNXSPACE_PRIVATE_KEY_URI: '/run/secrets/MNXSPACE_PRIVATE_KEY'
    secrets:
      - MNXSPACE_MONGO_URL
      - MNXSPACE_PRIVATE_KEY
      - MNXSPACE_DISCORD_CLIENT_SECRET
      - MNXSPACE_GITHUB_CLIENT_SECRET
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == co1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.maanexspace.loadbalancer.server.port=80
        - traefik.http.routers.maanexspace.entrypoints=https
        - traefik.http.routers.maanexspace.rule=Host(`maanexspace-prod-eu01.tude.network`)
        - traefik.http.routers.maanexspace.tls.certresolver=cloudflare
        - traefik.http.routers.maanexspace.tls.domains[0].main=maanexspace-prod-eu01.tude.network

networks:
  proxy:
    external: true

secrets:
  MNXSPACE_MONGO_URL:
    external: true
  MNXSPACE_PRIVATE_KEY:
    external: true
  MNXSPACE_DISCORD_CLIENT_SECRET:
    external: true
  MNXSPACE_GITHUB_CLIENT_SECRET:
    external: true
