version: "3.3"

services:
  greenlight:
    image: ghcr.io/maanex/greenlight:master
    secrets:
      - GREENLIGHT_DBOT_TOKEN
      - GREENLIGHT_DBOT_ID
      - GREENLIGHT_DBOT_PUBKEY
      - GREENLIGHT_MONGO_URL
    ports:
      - 5008:80
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s

  # wumpum:
  #   image: ghcr.io/maanex/wumpum:master
  #   environment:
  #     WUMPUM_TRACK_INDIVIDUAL: "true"
  #   networks:
  #     - metrics
  #   secrets:
  #     - WUMPUM_DBOT_TOKEN
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager
  #     labels:
  #       - prometheus-job=wumpum
  #     update_config:
  #       parallelism: 1
  #       delay: 10s

networks:
  metrics:
    external: true

secrets:
  GREENLIGHT_DBOT_TOKEN:
    external: true
  GREENLIGHT_DBOT_ID:
    external: true
  GREENLIGHT_DBOT_PUBKEY:
    external: true
  GREENLIGHT_MONGO_URL:
    external: true
  WUMPUM_DBOT_TOKEN:
    external: true
