version: "3.3"

services:
  greenlight:
    image: ghcr.io/maanex/greenlight:master
    secrets:
      - GREENLIGHT_DBOT_TOKEN
      - GREENLIGHT_DBOT_ID
      - GREENLIGHT_DBOT_PUBKEY
      - GREENLIGHT_MONGO_URL
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.greenlight.loadbalancer.server.port=80
        - traefik.http.routers.greenlight.entrypoints=https
        - traefik.http.routers.greenlight.rule=Host(`greenlight.maanex.me`)
        - traefik.http.routers.greenlight.tls.certresolver=cloudflare
        - traefik.http.routers.greenlight.tls.domains[0].main=greenlight.maanex.me

networks:
  proxy:
    external: true

secrets:
  GREENLIGHT_DBOT_TOKEN:
    external: true
  GREENLIGHT_DBOT_ID:
    external: true
  GREENLIGHT_DBOT_PUBKEY:
    external: true
  GREENLIGHT_MONGO_URL:
    external: true
  WUMPUM_DBOT_TOKEN:
    external: true
