version: "3.3"

services:
  bot:
    image: ghcr.io/maanex/tudebot4:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NODE_ENV: "production"
      TUDEBOT_GIBU_PIPELINE_ENDPOINT: "http://gibu_api_pipeline/execute"
      TUDEBOT_VAULT_PUBLIC_KEY_PATH: "/run/secrets/TUDEBOT_VAULT_PUBLIC_KEY"
      TUDEBOT_VAULT_PRIVATE_KEY_PATH: "/run/secrets/TUDEBOT_VAULT_PRIVATE_KEY"
    networks:
      - proxy
      - logging
      - metrics
      - gibu
    secrets:
      - TUDEBOT_DBOT_TOKEN
      - TUDEBOT_DBOT_ID
      - TUDEBOT_MONGO_URL
      - TUDEBOT_WIT_TOKEN
      - TUDEBOT_OBRAZIUM_TOKEN
      - TUDEBOT_GOOGLE_KEY
      - TUDEBOT_KSOFT_TOKEN
      - TUDEBOT_ALEXA_KEY
      - TUDEBOT_VAULT_PUBLIC_KEY
      - TUDEBOT_VAULT_PRIVATE_KEY
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - prometheus-job=tudebot
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.tudebot.loadbalancer.server.port=80
        - traefik.http.routers.tudebot.entrypoints=https
        - traefik.http.routers.tudebot.rule=Host(`tudebot.tude.network`)
        - traefik.http.routers.tudebot.tls.certresolver=cloudflare
        - traefik.http.routers.tudebot.tls.domains[0].main=tudebot.tude.network

networks:
  proxy:
    external: true
  logging:
    external: true
  metrics:
    external: true
  gibu:
    external: true

secrets:
  TUDEBOT_DBOT_TOKEN:
    external: true
  TUDEBOT_DBOT_ID:
    external: true
  TUDEBOT_MONGO_URL:
    external: true
  TUDEBOT_WIT_TOKEN:
    external: true
  TUDEBOT_OBRAZIUM_TOKEN:
    external: true
  TUDEBOT_GOOGLE_KEY:
    external: true
  TUDEBOT_KSOFT_TOKEN:
    external: true
  TUDEBOT_ALEXA_KEY:
    external: true
  TUDEBOT_VAULT_PUBLIC_KEY:
    external: true
  TUDEBOT_VAULT_PRIVATE_KEY:
    external: true
