version: "3.3"

services:
  ui:
    image: ghcr.io/tude-infra/account-ui:master
    environment:
      NODE_ENV: "production"
    networks:
      - proxy
      - metrics
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - prometheus-job=tudeidm-ui
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.idm-ui.loadbalancer.server.port=80
        - traefik.http.routers.idm-ui.entrypoints=https
        - traefik.http.routers.idm-ui.rule=Host(`account.tude.club`)
        - traefik.http.routers.idm-ui.tls.certresolver=cloudflare
        - traefik.http.routers.idm-ui.tls.domains[0].main=account.tude.club

  iam:
    image: ghcr.io/tude-infra/iam:master
    environment:
      NODE_ENV: "production"
    networks:
      - proxy
      - metrics
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - prometheus-job=tude-iam
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.tude-iam.loadbalancer.server.port=80
        - traefik.http.routers.tude-iam.entrypoints=https
        - traefik.http.routers.tude-iam.rule=Host(`iam.tude.network`)
        - traefik.http.routers.tude-iam.tls.certresolver=cloudflare
        - traefik.http.routers.tude-iam.tls.domains[0].main=iam.tude.network

networks:
  proxy:
    external: true
  metrics:
    external: true
