version: "3.3"

services:
  weaviate:
    image: semitechnologies/weaviate:1.22.3
    command:
      - --host
      - 0.0.0.0
      - --port
      - '80'
      - --scheme
      - http
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,img2vec-neural'
      CLUSTER_HOSTNAME: 'co1'
    networks:
      - weaviate_int
      - devenv
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co1
      update_config:
        parallelism: 1
        delay: 30s
      labels:
        - prometheus-job=weaviate

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
    networks:
      - weaviate_int
      - devenv
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co1

  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
    networks:
      - weaviate_int
      - devenv
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == co1

volumes:
  weaviate_data:

networks:
  weaviate_int:
    driver: overlay
  devenv:
    external: true
