version: "3.3"

services:
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.18.2"
      MEMORY: "4G"
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
      - target: 25565
        published: 25565
        protocol: udp
        mode: host
      - target: 80
        published: 80
        mode: host
    volumes:
      - /root/data:/data
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '3'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 3G
      placement:
        constraints:
          - node.hostname == mc
