version: "3.3"

services:
  thumbnailer:
    image: maanex/thumbnailer:latest
    environment:
      METRICS_AUTH: ""
    networks:
      - fsm-micros
      - metrics
    deploy:
      placement:
        constraints:
          - node.role == manager
  
  gaexporter:
    image: ghcr.io/maanex/googleanalytics_exporter:master
    environment:
      GA_VIEWID: "ga:215657062" # google analytics view id
      GA_INTERVAL: 60
      GA_PORT: 80
      GA_METRICS: "rt:pageviews rt:activeUsers"
    networks:
      - metrics
    secrets:
      - GA_CREDS
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - prometheus-job=ga
      placement:
        constraints:
          - node.role == manager

networks:
  fsm-micros:
    external: true
  metrics:
    external: true

volumes:
  logfiles: {}

secrets:
  GA_CREDS:
    external: true
