version: "3.3"

services:
  bot:
    image: ghcr.io/maanex/tudebot4:master
    networks:
      - logging
      - metrics
    secrets:
      - TUDEBOT_DBOT_TOKEN
      - TUDEBOT_DBOT_ID
      - TUDEBOT_MONGO_URL
      - TUDEBOT_WIT_TOKEN
      - TUDEBOT_OBRAZIUM_TOKEN
      - TUDEBOT_GOOGLE_KEY
      - TUDEBOT_KSOFT_TOKEN
      - TUDEBOT_ALEXA_KEY
      - TUDEBOT_GIBU_ENDPOINT
    deploy:
      # labels:
      #   - prometheus-job=tudebot
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s

networks:
  logging:
    external: true
  metrics:
    external: true

secrets:
  TUDEBOT_DBOT_TOKEN:
    external: true
  TUDEBOT_DBOT_ID:
    external: true
  TUDEBOT_MONGO_URL:
    external: true
  TUDEBOT_WIT_TOKEN:
    external: true
  TUDEBOT_OBRAZIUM_TOKEN:
    external: true
  TUDEBOT_GOOGLE_KEY:
    external: true
  TUDEBOT_KSOFT_TOKEN:
    external: true
  TUDEBOT_ALEXA_KEY:
    external: true
  TUDEBOT_GIBU_ENDPOINT:
    external: true
