version: "3.3"

services:
  # lumberer:
  #   image: maanex/lumberer:latest
  #   volumes:
  #     - logfiles:/storage
  #   environment:
  #     STORAGE_PATH: "/storage"
  #   networks:
  #     - logging
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager

  # thumbnailer:
  #   image: maanex/thumbnailer:latest
  #   environment:
  #     FREESTUFF_KEY: "verysecret"
  #     METRICS_AUTH: "yikes"
  #   networks:
  #     - traefik-public
  #   ports:
  #     - 9915:9915 # TODO remove with traefik
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.network=traefik-public
  #       - traefik.http.services.thumbnailer.loadbalancer.server.port=9915
  #       - traefik.http.routers.thumbnailer.entrypoints=https
  #       - traefik.http.routers.thumbnailer.rule=Host(`thumbnails.freestuffbot.xyz`)
  #       - traefik.http.routers.thumbnailer.tls.certresolver=letsencrypt
  
  gaexporter:
    image: ghcr.io/maanex/googleanalytics_exporter:master
    environment:
      GA_VIEWID: "ga:215657062" # google analytics view id
      GA_INTERVAL: 60
      GA_PORT: 80
      GA_METRICS: "rt:pageviews rt:activeUsers"
    networks:
      - metrics
    secrets:
      - GA_CREDS
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - prometheus-job=fsb
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true
  logging:
    external: true
  metrics:
    external: true

volumes:
  logfiles: {}

secrets:
  GA_CREDS:
    external: true
