version: "3.3"

services:
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.18"
      MEMORY: "4G"
    ports:
      - 25565:25565
      - 80:80
    volumes:
      - /root/data:/data
    tty: true
    stdin_open: true
    # restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '3'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 3G
      placement:
        constraints:
          - node.hostname == mc
