version: "3.3"

services:
  api_games:
    image: ghcr.io/maanex-gibu/api_games:master
    environment:
      - PORT=80
    networks:
      - gibu
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == coyote
      update_config:
        parallelism: 1
        delay: 10s

networks:
  gibu:
    external: true
