version: "3.9"

services:
  chrome:
    image: zenika/alpine-chrome
    entrypoint: [
      "chromium-browser",
      "--headless",
      "--disable-gpu",
      "--disable-software-rasterizer",
      "--disable-dev-shm-usage",
      "--no-sandbox",
      "--remote-debugging-address=0.0.0.0",
      "--remote-debugging-port=9222"
    ]
    ports:
      - 9222:9222