file_version = 1
name = "Tude Bot"

[service]
image = "ghcr.io/maanex/tudebot4:master"

[[volume]]
inside = "/var/run/docker.sock"
outside = "/var/run/docker.sock"
mode = "ro"

[environment]
NODE_ENV = "production"
TUDEBOT_GIBU_PIPELINE_ENDPOINT = "http://gibu_api_pipeline/execute"
TUDEBOT_VAULT_PUBLIC_KEY_PATH = "/run/secrets/TUDEBOT_VAULT_PUBLIC_KEY"
TUDEBOT_VAULT_PRIVATE_KEY_PATH = "/run/secrets/TUDEBOT_VAULT_PRIVATE_KEY"

[secrets]
TUDEBOT_DBOT_TOKEN = true
TUDEBOT_DBOT_ID = true
TUDEBOT_MONGO_URL = true
TUDEBOT_WIT_TOKEN = true
TUDEBOT_OBRAZIUM_TOKEN = true
TUDEBOT_GOOGLE_KEY = true
TUDEBOT_KSOFT_TOKEN = true
TUDEBOT_ALEXA_KEY = true
TUDEBOT_VAULT_PUBLIC_KEY = true
TUDEBOT_VAULT_PRIVATE_KEY = true

[networks]
proxy = true
logging = true
metrics = true
gibu = true

[deploy]
mode = "replicated"
replicas = 1

[deploy.placement]
constraints = [
  "node.role==manager",
  "node.labels.autoscale==true"
]

[deploy.updates]
parallelism = 1
delay = "30s"

[deploy.labels]
"prometheus-job" = "tudebot"
"traefik.enable" = true
"traefik.docker.network" = "proxy"
"traefik.http.services.tudebot.loadbalancer.server.port" = 80
"traefik.http.routers.tudebot.entrypoints" = "https"
"traefik.http.routers.tudebot.rule" = "Host(`tudebot.tude.network`)"
"traefik.http.routers.tudebot.tls.certresolver" = "cloudflare"
"traefik.http.routers.tudebot.tls.domains[0].main" = "tudebot.tude.network"
